# .platform.app.yaml
name: sylius

type: "php:7.1"
build:
    flavor: composer

relationships:
    database: "mysql:mysql"
    redis: "redis:redis"

runtime:
    extensions:
        - msgpack
        - igbinary
        - memcached
        - redis

dependencies:
    nodejs:
        yarn: "*"
        gulp-cli: "*"

web:
    document_root: "/web"
    passthru: "/app.php"

    whitelist:
      - \.css$
      - \.js$

      - \.gif$
      - \.jpe?g$
      - \.png$
      - \.tiff?$
      - \.wbmp$
      - \.ico$
      - \.jng$
      - \.bmp$
      - \.svgz?$

      - \.midi?$
      - \.mpe?ga$
      - \.mp2$
      - \.mp3$
      - \.m4a$
      - \.ra$
      - \.weba$

      - \.3gpp?$
      - \.mp4$
      - \.mpe?g$
      - \.mpe$
      - \.ogv$
      - \.mov$
      - \.webm$
      - \.flv$
      - \.mng$
      - \.asx$
      - \.asf$
      - \.wmv$
      - \.avi$

      - \.ogx$

      - \.swf$

      - \.jar$

      - \.ttf$
      - \.eot$
      - \.woff$
      - \.woff2$
      - \.otf$

      - /robots\.txt$

      - \.html$
      - \.pdf$

disk: 4096

mounts:
    "/var/cache": "shared:files/cache"
    "/var/logs": "shared:files/logs"
    "/web/uploads": "shared:files/uploads"
    "/web/media": "shared:files/media"

hooks:
    build: |
        rm web/app_dev.php
        rm web/app_test.php
        rm web/app_test_cached.php
        rm -rf var/cache/*
        php bin/console --env=prod --no-debug --ansi cache:clear --no-warmup
        php bin/console --env=prod --no-debug --ansi cache:warmup
        php bin/console --env=prod --no-debug --ansi assets:install
        # Next command is only needed if you are using themes
        php bin/console --env=prod --no-debug --ansi theme:assets:install
        yarn install
        GULP_ENV=prod yarn run gulp
    deploy: |
        rm -rf var/cache/*
        php bin/console --env=prod doctrine:migrations:migrate --no-interaction